# --- Docker Profile Configuration ---

# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://postgres:5432/ledger_system_db
spring.datasource.username=madhukiran
spring.datasource.password=admin123

# JPA & Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Caching properties
spring.data.redis.host=redis
spring.data.redis.port=6379

# OpenAPI Docs Endpoint
springdoc.swagger-ui.path=/swagger-ui.html
