spring.application.name=ledger-engine

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_system_db
spring.datasource.username=madhukiran
spring.datasource.password=admin123

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration (For Idempotency and Locking)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
